# This is a TOML document. Boom.

[readerMinApp]
app_id = "wx4d466242a9ecc265"
app_secret = "0e353a37bcc03dea9ec30926173834e0"

[database]
type = "postgres"
host = "119.23.237.215"
user = "xiaoyi"
password = "123456"
sslmode = "disable"
dbname = "readerminapp"
port = 5432


[search]
limit_level = false
dev_version = "1.0.3"

[ad]
screen = "adunit-da16d0f32013ecb0"
reward = "adunit-c269e8732f5ae00c"
home_banner = "adunit-97bfa88d1c446274"
list_banner = "adunit-a7438aa03206231f"
info_banner = "adunit-1b169a05a6785147"
home_video = "adunit-2f7190abab0323b1"
list_video = "adunit-3b89982cba1ecd7e"
info_video = "adunit-d5b4a862d8daadf3"
pre_video = "adunit-1c8adb51667c8652"
