# This is a TOML document. Boom.

[readerMinApp]
app_id = "wxa94ddd94358b2d1d"
app_secret = "1bc426774cced93e8b9e322c6aadaac4"

[database]
type = "postgres"
host = "119.23.237.215"
user = "xiaoyi"
password = "123456"
sslmode = "disable"
dbname = "readerminapp"
port = 5432

[search]
limit_level = true


[ad]
screen = "adunit-da16d0f32013ecb0"
reward = "adunit-c269e8732f5ae00c"
list_banner = "adunit-a7438aa03206231f"
info_banner = "adunit-1b169a05a6785147"